spring.application.name=mediatrack

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mediatrack
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
